/**
 * Petri Asset Library & Gallery Service
 * Manages media assets (videos, images, audio, 3D models, datasets, documents)
 * generated by Hyperframe, Video Flow, Diffusion, Submersion, and EDM Studio.
 */

import { AssetItem, AssetItemType } from '../types';

const STORAGE_KEY = 'petri_asset_library_v1';

const DEFAULT_ASSETS: AssetItem[] = [
  // --- VIDEOS ---
  {
    id: 'asset-vid-001',
    name: 'Hyperframe Fluid Hydrodynamics Simulation',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=60',
    sizeBytes: 15420000,
    createdAt: Date.now() - 3600 * 1000 * 4,
    source: 'Hyperframe Video Engine',
    tags: ['fluid', 'simulation', '4k', 'tiffany-palette'],
    dimensions: '3840x2160',
    durationSeconds: 15,
    metadata: {
      fps: 60,
      codec: 'H.265 / HEVC',
      seed: 849204,
      prompt: 'Hydrodynamic Kelvin-Helmholtz wave billows in tiffany cyan and obsidian slate',
    },
  },
  {
    id: 'asset-vid-002',
    name: 'Video Flow: Act I Scene 01 - Cyber District',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=60',
    sizeBytes: 9800000,
    createdAt: Date.now() - 3600 * 1000 * 12,
    source: 'Petri Video Flow NLE',
    tags: ['nle', 'scene-01', 'optical-flow', '1080p'],
    dimensions: '1920x1080',
    durationSeconds: 15,
    metadata: {
      fps: 30,
      transition: 'optical_flow_morph',
      trackCount: 3,
    },
  },
  {
    id: 'asset-vid-003',
    name: 'Submersion 3D Camera Orbit & Trajectory',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=60',
    sizeBytes: 24800000,
    createdAt: Date.now() - 3600 * 1000 * 24,
    source: 'Submersion 3D Engine',
    tags: ['submersion', 'trajectory', 'flythrough', 'waterline'],
    dimensions: '1920x1080',
    durationSeconds: 30,
    metadata: {
      elevationCutoff: 0.0,
      cameraTrack: 'Spiral Helix',
    },
  },

  // --- IMAGES ---
  {
    id: 'asset-img-001',
    name: 'Petri Architectural Workdesk Neo-Teal',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=60',
    sizeBytes: 3840000,
    createdAt: Date.now() - 3600 * 1000 * 2,
    source: 'Petri Diffusion Studio',
    tags: ['workdesk', 'render', 'tiffany-pastel', 'architecture'],
    dimensions: '2560x1440',
    metadata: {
      sampler: 'Euler A',
      steps: 35,
      cfgScale: 7.0,
    },
  },
  {
    id: 'asset-img-002',
    name: 'Lieflat Circadian Clock-In Polar Matrix',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=1600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=60',
    sizeBytes: 2100000,
    createdAt: Date.now() - 3600 * 1000 * 8,
    source: 'EDM Studio Export',
    tags: ['lieflat', 'radial', 'infographic', 'clock-in'],
    dimensions: '1800x1800',
    metadata: {
      chartType: 'Polar Circadian Clock',
      cohortSize: 849,
    },
  },
  {
    id: 'asset-img-003',
    name: 'Quantum ZZFeatureMap State Fidelity Vector',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=1600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=600&auto=format&fit=crop&q=60',
    sizeBytes: 1950000,
    createdAt: Date.now() - 3600 * 1000 * 18,
    source: 'Qiskit DevContainer Agent',
    tags: ['quantum', 'kernel', 'zzfeaturemap', 'fidelity'],
    dimensions: '1920x1080',
    metadata: {
      fidelityScore: '98.4%',
      entanglement: 'linear',
    },
  },

  // --- AUDIO ---
  {
    id: 'asset-aud-001',
    name: 'Submersion Ambient Drift (Binaural 432Hz)',
    type: 'audio',
    url: 'https://actions.google.com/sounds/v1/ambiences/humming_room.ogg',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=60',
    sizeBytes: 4200000,
    createdAt: Date.now() - 3600 * 1000 * 6,
    source: 'Petri Audio Generator',
    tags: ['ambient', 'binaural', 'synth', 'focus'],
    durationSeconds: 180,
    metadata: {
      bitrate: '320kbps',
      sampleRate: '48kHz',
    },
  },
  {
    id: 'asset-aud-002',
    name: 'Voiceover: Longitudinal EDM Analysis Summary',
    type: 'audio',
    url: 'https://actions.google.com/sounds/v1/science_fiction/alien_beacon.ogg',
    thumbnailUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&auto=format&fit=crop&q=60',
    sizeBytes: 1850000,
    createdAt: Date.now() - 3600 * 1000 * 16,
    source: 'Neural TTS Voice Clone',
    tags: ['voiceover', 'summary', 'tts', 'academic'],
    durationSeconds: 72,
    metadata: {
      voiceModel: 'Gemini-Flash-Voice-Studio',
      language: 'en-US',
    },
  },

  // --- 3D CAPTURES ---
  {
    id: 'asset-3d-001',
    name: 'LiDAR Volumetric Submersion Topography',
    type: '3d',
    url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    thumbnailUrl: 'https://images.unsplash.com/photo-1633493106185-3ac5e6e39218?w=600&auto=format&fit=crop&q=60',
    sizeBytes: 28400000,
    createdAt: Date.now() - 3600 * 1000 * 30,
    source: 'Submersion Spatial Scanner',
    tags: ['lidar', 'gaussian-splat', 'mesh', 'elevation'],
    dimensions: '120k Polygons',
    metadata: {
      format: 'GLB / glTF 2.0',
      vertexCount: 124890,
      waterlineAnchorZ: 0.0,
    },
  },
  {
    id: 'asset-3d-002',
    name: 'Petri Micro-Node Physical Cluster Frame',
    type: '3d',
    url: 'https://modelviewer.dev/shared-assets/models/RobotExpressive.glb',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=60',
    sizeBytes: 14200000,
    createdAt: Date.now() - 3600 * 1000 * 48,
    source: 'Zero CAD Exporter',
    tags: ['cad', 'chassis', 'rtx4090', 'bevy-avian'],
    dimensions: '45k Triangles',
    metadata: {
      format: 'GLB',
      scale: '1:1',
    },
  },

  // --- DATASETS ---
  {
    id: 'asset-dat-001',
    name: 'BBS Midterm 849 Student Attendance & Scores',
    type: 'dataset',
    url: '#',
    sizeBytes: 520000,
    createdAt: Date.now() - 3600 * 1000 * 10,
    source: 'EDM Studio (Google Drive DWD)',
    tags: ['federated', 'attendance', 'clock-in', 'midterm', '849-records'],
    metadata: {
      rows: 849,
      columns: 14,
      fileType: 'JSONL / CSV',
      encryption: 'AES-256 GCM',
    },
  },
  {
    id: 'asset-dat-002',
    name: 'Q-Matrix Cognitive Item Specification ($J=25, K=5$)',
    type: 'dataset',
    url: '#',
    sizeBytes: 74000,
    createdAt: Date.now() - 3600 * 1000 * 20,
    source: 'EDM Studio Q-Matrix Builder',
    tags: ['q-matrix', 'dina', 'psychometrics', 'latent-skills'],
    metadata: {
      items: 25,
      skills: 5,
      format: 'JSON / Q-Format',
    },
  },
  {
    id: 'asset-dat-003',
    name: 'Lakehouse BigQuery Academic Mastery Federated Parquet',
    type: 'dataset',
    url: '#',
    sizeBytes: 3400000,
    createdAt: Date.now() - 3600 * 1000 * 72,
    source: 'Google Cloud BigQuery DTS',
    tags: ['bigquery', 'lakehouse', 'parquet', 'analytics'],
    metadata: {
      rows: 15420,
      compression: 'SNAPPY',
    },
  },

  // --- DOCUMENTS ---
  {
    id: 'asset-doc-001',
    name: 'Lieflat Submersion 110+ Visualization Almanac Specification',
    type: 'document',
    url: '#',
    sizeBytes: 240000,
    createdAt: Date.now() - 3600 * 1000 * 5,
    source: 'Petri Technical Architecture',
    tags: ['lieflat', 'specification', 'almanac', 'markdown'],
    metadata: {
      pages: 42,
      format: 'Markdown / PDF',
    },
  },
  {
    id: 'asset-doc-002',
    name: 'Quantum-Enhanced EDM Psychometrics Technical Report',
    type: 'document',
    url: '#',
    sizeBytes: 1120000,
    createdAt: Date.now() - 3600 * 1000 * 36,
    source: 'EDM Research Group',
    tags: ['whitepaper', 'dina-qsvc', 'ferpa', 'academic'],
    metadata: {
      pages: 18,
      authors: 'Petri Autonomous Synthesis Engine',
    },
  },
];

export class AssetLibraryService {
  private assets: AssetItem[] = [];

  constructor() {
    this.loadAssets();
  }

  private loadAssets(): void {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored) {
        this.assets = JSON.parse(stored);
      } else {
        this.assets = DEFAULT_ASSETS;
        this.saveAssets();
      }
    } catch (e) {
      console.warn('Could not read asset library from localStorage, using defaults:', e);
      this.assets = DEFAULT_ASSETS;
    }
  }

  private saveAssets(): void {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(this.assets));
    } catch (e) {
      console.warn('Could not save assets to localStorage:', e);
    }
  }

  getAssets(): AssetItem[] {
    return [...this.assets];
  }

  getAssetById(id: string): AssetItem | undefined {
    return this.assets.find((a) => a.id === id);
  }

  addAsset(asset: Omit<AssetItem, 'id' | 'createdAt'>): AssetItem {
    const newAsset: AssetItem = {
      ...asset,
      id: `asset-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      createdAt: Date.now(),
    };
    this.assets.unshift(newAsset);
    this.saveAssets();
    return newAsset;
  }

  deleteAsset(id: string): boolean {
    const initialLen = this.assets.length;
    this.assets = this.assets.filter((a) => a.id !== id);
    if (this.assets.length !== initialLen) {
      this.saveAssets();
      return true;
    }
    return false;
  }

  filterAssets(
    category: AssetItemType | 'all',
    searchQuery: string = '',
    sortBy: 'newest' | 'name' | 'size' = 'newest'
  ): AssetItem[] {
    let result = [...this.assets];

    if (category !== 'all') {
      result = result.filter((a) => a.type === category);
    }

    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase().trim();
      result = result.filter(
        (a) =>
          a.name.toLowerCase().includes(query) ||
          a.source.toLowerCase().includes(query) ||
          a.tags.some((t) => t.toLowerCase().includes(query))
      );
    }

    if (sortBy === 'newest') {
      result.sort((a, b) => b.createdAt - a.createdAt);
    } else if (sortBy === 'name') {
      result.sort((a, b) => a.name.localeCompare(b.name));
    } else if (sortBy === 'size') {
      result.sort((a, b) => b.sizeBytes - a.sizeBytes);
    }

    return result;
  }

  getTotalStorageBytes(): number {
    return this.assets.reduce((sum, a) => sum + a.sizeBytes, 0);
  }

  resetToDefaults(): void {
    this.assets = DEFAULT_ASSETS;
    this.saveAssets();
  }
}

export const assetLibraryService = new AssetLibraryService();
