/**
 * Lieflat 100+ Chart Encyclopedia & Catalog Service
 * Grounded in https://github.com/larashero3-dotcom/lieflat-charts/blob/main/README.en.md
 * Indexes 110+ distinct Lieflat & Petri Submersion chart options across 10 archetypes.
 */

export type LieflatArchetype =
  | 'midterm_exam'
  | 'clock_in_temporal'
  | 'wave_ridge'
  | 'lollipop_almanac'
  | 'glance_sprint'
  | 'stream_funnel'
  | 'force_network'
  | 'submersion_3d'
  | 'hierarchical_partition'
  | 'tactical_matrix';

export interface ChartOptionDefinition {
  id: string;
  name: string;
  archetype: LieflatArchetype;
  category: string;
  description: string;
  mathFormula?: string;
  dimensionality: '2D' | '2.5D' | '3D Submersion';
  tags: string[];
  recommendedFor: string;
  waterlineInteractive: boolean;
}

export const LIEFLAT_ARCHETYPES_METADATA: {
  id: LieflatArchetype;
  title: string;
  description: string;
  count: number;
}[] = [
  {
    id: 'midterm_exam',
    title: 'Midterm Exam & Psychometrics',
    description: 'Item Response Theory (IRT), bimodal score bells, and DINA cognitive mastery distributions.',
    count: 12,
  },
  {
    id: 'clock_in_temporal',
    title: 'Clock-In & 24-Hour Temporal Cadence',
    description: '24-hour radial punch dials, circadian attendance sunbursts, and arrival latency spirals.',
    count: 12,
  },
  {
    id: 'wave_ridge',
    title: 'Wave Ridges & Submersion Elevations',
    description: 'Multi-layer Gaussian density ridges, waterline contour slicing, and spectral wavelets.',
    count: 12,
  },
  {
    id: 'lollipop_almanac',
    title: 'Lollipops & Stem Almanacs',
    description: 'Diverging barbell stems, radial polar lollipops, and stepped attendance cadences.',
    count: 12,
  },
  {
    id: 'glance_sprint',
    title: 'Glance & Micro-Sprint Strips',
    description: 'Barcode heat strips, horizon pulses, latency interval tics, and attendance ribbons.',
    count: 12,
  },
  {
    id: 'stream_funnel',
    title: 'Hourglass Streams & Funnel Flows',
    description: 'Giorgia Lupi poured funnels, dual-cone pinch points, and alluvial conduits.',
    count: 10,
  },
  {
    id: 'force_network',
    title: 'Force-Directed & Network Topologies',
    description: 'Bipartite student-skill meshes, radial constellations, and modular Louvain clusters.',
    count: 10,
  },
  {
    id: 'submersion_3d',
    title: '3D Submersion Manifolds & Terrains',
    description: 'WebGL volumetric terrain elevations, particle vortex cyclones, and bathymetric trenches.',
    count: 10,
  },
  {
    id: 'hierarchical_partition',
    title: 'Hierarchical & Compositional Partitions',
    description: 'Submersion treemaps, nested sunbursts, Voronoi tessellations, and flame graphs.',
    count: 10,
  },
  {
    id: 'tactical_matrix',
    title: 'Tactical Matrices & Multiaxial Views',
    description: 'Correlation heatmaps, parallel coordinates, Andrews curves, and radar polygons.',
    count: 10,
  },
];

export const LIEFLAT_100_CHART_CATALOG: ChartOptionDefinition[] = [
  // 1. MIDTERM EXAM & PSYCHOMETRICS (12)
  {
    id: 'midterm-irt-2pl',
    name: 'IRT 2-Parameter Logistic Curve',
    archetype: 'midterm_exam',
    category: 'Item Response Theory',
    description: 'Models item probability P(theta) = 1 / (1 + exp(-a * (theta - b))) across latent student ability.',
    mathFormula: 'P_i(\\theta) = \\frac{1}{1 + e^{-a_i(\\theta - b_i)}}',
    dimensionality: '2D',
    tags: ['midterm', 'irt', 'probability', 'psychometrics'],
    recommendedFor: 'Evaluating item difficulty vs discrimination across midterm test questions.',
    waterlineInteractive: true,
  },
  {
    id: 'midterm-bimodal-bell',
    name: 'Bimodal Score Distribution Bell',
    archetype: 'midterm_exam',
    category: 'Score Density',
    description: 'Gaussian mixture decomposition revealing high-mastery vs at-risk intervention cohorts.',
    mathFormula: 'f(x) = w_1 \\mathcal{N}(\\mu_1, \\sigma_1^2) + w_2 \\mathcal{N}(\\mu_2, \\sigma_2^2)',
    dimensionality: '2.5D',
    tags: ['midterm', 'distribution', 'bell-curve', 'cohorts'],
    recommendedFor: 'Visualizing grade bifurcations and setting defensible passing thresholds.',
    waterlineInteractive: true,
  },
  {
    id: 'midterm-dina-qmatrix',
    name: 'DINA Q-Matrix Mastery Heatmap',
    archetype: 'midterm_exam',
    category: 'Cognitive Diagnostic',
    description: 'Cognitive attribute mastery profiles with slip (s_j) and guessing (g_j) parameter matrices.',
    mathFormula: 'P(Y_{ij}=1 | \\alpha_i) = g_j^{1-\\eta_{ij}} (1-s_j)^{\\eta_{ij}}',
    dimensionality: '2D',
    tags: ['midterm', 'dina', 'q-matrix', 'mastery'],
    recommendedFor: 'Diagnosing which specific curriculum skills students failed to master in the midterm.',
    waterlineInteractive: true,
  },
  {
    id: 'midterm-passing-cutoff-stepper',
    name: 'Interactive Passing Cutoff Stepper',
    archetype: 'midterm_exam',
    category: 'Threshold Simulation',
    description: 'Dynamic waterline slider showing pass/submerge ratios as cutoff moves from 50% to 85%.',
    dimensionality: '2D',
    tags: ['midterm', 'cutoff', 'passing-grade', 'waterline'],
    recommendedFor: 'Simulating grade scale adjustments and tracking at-risk early warning counts.',
    waterlineInteractive: true,
  },
  {
    id: 'midterm-item-discrimination-scatter',
    name: 'Item Difficulty vs Discrimination Quad',
    archetype: 'midterm_exam',
    category: 'Item Quality',
    description: 'Four-quadrant scatter indexing good discriminators vs flawed ambiguous exam questions.',
    dimensionality: '2D',
    tags: ['midterm', 'discrimination', 'item-analysis'],
    recommendedFor: 'Identifying exam questions that need revision or curve adjustments.',
    waterlineInteractive: false,
  },
  {
    id: 'midterm-percentile-rank-ogive',
    name: 'Cumulative Percentile Rank Ogive',
    archetype: 'midterm_exam',
    category: 'Ranking',
    description: 'Smooth cumulative frequency S-curve with decile markers and median demarcation.',
    dimensionality: '2D',
    tags: ['midterm', 'percentiles', 'ogive', 'ranking'],
    recommendedFor: 'Determining exact percentile standings across all 849 students.',
    waterlineInteractive: true,
  },
  {
    id: 'midterm-slippage-bubble-matrix',
    name: 'Attribute Slippage Bubble Matrix',
    archetype: 'midterm_exam',
    category: 'Error Diagnostics',
    description: 'Displays unintentional slip rate per question weighted by student cognitive mastery.',
    dimensionality: '2.5D',
    tags: ['midterm', 'slippage', 'bubble-chart'],
    recommendedFor: 'Detecting careless errors on easy questions by high-ability students.',
    waterlineInteractive: false,
  },
  {
    id: 'midterm-box-violin-hybrid',
    name: 'Quartile Box-Violin Hybrid Ribbon',
    archetype: 'midterm_exam',
    category: 'Distribution Shape',
    description: 'Combines Tukey interquartile boxes with mirrored kernel density contours per section.',
    dimensionality: '2D',
    tags: ['midterm', 'violin', 'boxplot', 'quartiles'],
    recommendedFor: 'Comparing score distribution shapes between morning and afternoon cohorts.',
    waterlineInteractive: true,
  },
  {
    id: 'midterm-speed-accuracy-horizon',
    name: 'Exam Speed vs Accuracy Horizon',
    archetype: 'midterm_exam',
    category: 'Testing Dynamics',
    description: 'Completion latency plotted against accuracy score showing rushed vs methodical finishers.',
    dimensionality: '2.5D',
    tags: ['midterm', 'latency', 'speed-accuracy'],
    recommendedFor: 'Identifying test-taking anxiety and fatigue effects in the final 30 minutes.',
    waterlineInteractive: false,
  },
  {
    id: 'midterm-split-half-reliability',
    name: 'Split-Half Reliability Bland-Altman',
    archetype: 'midterm_exam',
    category: 'Test Reliability',
    description: 'Spearman-Brown corrected correlation between odd and even exam item sub-scores.',
    mathFormula: 'r_{sb} = \\frac{2r_{oe}}{1 + r_{oe}}',
    dimensionality: '2D',
    tags: ['midterm', 'reliability', 'spearman-brown'],
    recommendedFor: 'Proving psychometric test consistency and internal validity (alpha > 0.88).',
    waterlineInteractive: false,
  },
  {
    id: 'midterm-remediation-trajectory',
    name: 'Post-Midterm Remediation Trajectory',
    archetype: 'midterm_exam',
    category: 'Longitudinal Forecast',
    description: 'Vector field modeling expected recovery trajectories following targeted sprint interventions.',
    dimensionality: '2.5D',
    tags: ['midterm', 'remediation', 'trajectories'],
    recommendedFor: 'Setting post-midterm tutoring goals and monitoring recovery velocity.',
    waterlineInteractive: true,
  },
  {
    id: 'midterm-submersion-risk-barrier',
    name: 'Submersion Risk Boundary Wall',
    archetype: 'midterm_exam',
    category: 'Risk Classification',
    description: 'Three-layer waterline plane partitioning optimal, monitored, and submerged student groups.',
    dimensionality: '3D Submersion',
    tags: ['midterm', 'submersion', 'risk-wall', '3d'],
    recommendedFor: 'Executive overview of institutional risk exposure following midterm evaluations.',
    waterlineInteractive: true,
  },

  // 2. CLOCK-IN & 24-HOUR TEMPORAL CADENCE (12)
  {
    id: 'clockin-24h-radial-dial',
    name: '24-Hour Circular Radial Punch Clock',
    archetype: 'clock_in_temporal',
    category: 'Radial Cadence',
    description: 'Circular 24-hour clock face showing arrival density vectors, morning rush, and late stamps.',
    dimensionality: '2D',
    tags: ['clockin', 'radial', '24h', 'punch-clock', 'attendance'],
    recommendedFor: 'Visualizing exact clock-in arrival time distributions with interactive second hands.',
    waterlineInteractive: true,
  },
  {
    id: 'clockin-circadian-sunburst',
    name: 'Circadian Attendance Sunburst',
    archetype: 'clock_in_temporal',
    category: 'Polar Density',
    description: 'Concentric rings mapping hourly attendance intensity across all 7 days of the week.',
    dimensionality: '2.5D',
    tags: ['clockin', 'circadian', 'sunburst', 'hourly'],
    recommendedFor: 'Identifying peak operational hours, midday lulls, and study hall congestion.',
    waterlineInteractive: false,
  },
  {
    id: 'clockin-arrival-latency-spiral',
    name: 'Shift Arrival Latency Archimedean Spiral',
    archetype: 'clock_in_temporal',
    category: 'Spiral Chrono',
    description: 'Continuous spiral outward through 16 semester weeks plotting daily arrival delay minutes.',
    dimensionality: '2.5D',
    tags: ['clockin', 'spiral', 'lateness', 'longitudinal'],
    recommendedFor: 'Detecting cumulative habit drift and chronic tardiness progression over the term.',
    waterlineInteractive: true,
  },
  {
    id: 'clockin-morning-rush-concentric',
    name: 'Morning Rush Concentric Ring Gauge',
    archetype: 'clock_in_temporal',
    category: 'Peak Interval',
    description: 'Detailed 07:00–09:00 AM high-resolution punch distribution in 5-minute bucket bands.',
    dimensionality: '2D',
    tags: ['clockin', 'morning-rush', 'concentric'],
    recommendedFor: 'Monitoring campus entrance bottleneck capacity and early arrival bonuses.',
    waterlineInteractive: true,
  },
  {
    id: 'clockin-weekly-punch-heat-grid',
    name: '16-Week Mon-Fri Punch Card Heatmap',
    archetype: 'clock_in_temporal',
    category: 'Calendar Matrix',
    description: 'GitHub-style punch matrix mapping attendance consistency across all 80 instructional days.',
    dimensionality: '2D',
    tags: ['clockin', 'calendar', 'heatmap', 'punch-card'],
    recommendedFor: 'Spotting Friday dropouts, post-holiday dips, and sprint week spikes.',
    waterlineInteractive: true,
  },
  {
    id: 'clockin-lateness-deviation-compass',
    name: 'Punctuality Deviation Compass',
    archetype: 'clock_in_temporal',
    category: 'Directional Error',
    description: 'Polar vector plot showing +/- minute deviations from target 08:00 AM bell schedule.',
    dimensionality: '2D',
    tags: ['clockin', 'compass', 'punctuality'],
    recommendedFor: 'Individual student attendance coaching and punctuality scorecards.',
    waterlineInteractive: false,
  },
  {
    id: 'clockin-multi-shift-orbit',
    name: 'Multi-Shift Cohort Time Orbit',
    archetype: 'clock_in_temporal',
    category: 'Orbital Flow',
    description: 'Planetary orbital tracks showing morning, afternoon, and evening lab check-in overlap.',
    dimensionality: '2.5D',
    tags: ['clockin', 'orbit', 'shifts'],
    recommendedFor: 'Managing multi-cohort laboratory capacity and instructor scheduling.',
    waterlineInteractive: false,
  },
  {
    id: 'clockin-temporal-anomaly-radar',
    name: 'Clock-In Anomaly Detection Radar',
    archetype: 'clock_in_temporal',
    category: 'Outlier Detection',
    description: 'Flags irregular clock-in timestamps (off-hours, double-punch, weekend logins).',
    dimensionality: '2D',
    tags: ['clockin', 'anomaly', 'radar', 'audit'],
    recommendedFor: 'Automated campus security audits and timesheet anomaly verification.',
    waterlineInteractive: true,
  },
  {
    id: 'clockin-exam-correlation-scatter',
    name: 'Clock-In Punctuality vs Exam Score Correlation',
    archetype: 'clock_in_temporal',
    category: 'Empirical Correlation',
    description: 'Regression scatter proving that students arriving before 08:00 AM average 86.4% on exams.',
    dimensionality: '2.5D',
    tags: ['clockin', 'midterm', 'correlation', 'regression'],
    recommendedFor: 'Demonstrating pedagogical evidence that attendance punctuality drives academic success.',
    waterlineInteractive: true,
  },
  {
    id: 'clockin-punch-interval-ribbon',
    name: 'Continuous Punch Interval Stream Ribbon',
    archetype: 'clock_in_temporal',
    category: 'Flow Stream',
    description: 'Fluid ribbon height proportional to instantaneous student check-in throughput.',
    dimensionality: '2D',
    tags: ['clockin', 'stream', 'throughput'],
    recommendedFor: 'Real-time turnstile monitoring during morning campus ingress.',
    waterlineInteractive: true,
  },
  {
    id: 'clockin-time-bank-gauge',
    name: 'Instructional Hours Time-Bank Gauge',
    archetype: 'clock_in_temporal',
    category: 'Accrual Metric',
    description: 'Progressive fill gauge tracking total accumulated clock-in hours toward graduation reqs.',
    dimensionality: '2D',
    tags: ['clockin', 'gauge', 'time-bank'],
    recommendedFor: 'Accreditation compliance and state-mandated contact hour tracking.',
    waterlineInteractive: false,
  },
  {
    id: 'clockin-chrono-submersion-vortex',
    name: 'Temporal Submersion Clock Vortex',
    archetype: 'clock_in_temporal',
    category: '3D Chrono',
    description: '3D helical funnel where vertical depth represents elapsed weeks and angle is clock-in hour.',
    dimensionality: '3D Submersion',
    tags: ['clockin', 'vortex', '3d', 'submersion'],
    recommendedFor: 'Immersive exploration of 849 students navigating the full semester timeline.',
    waterlineInteractive: true,
  },

  // 3. WAVE RIDGES (12)
  {
    id: 'wave-waterline-contour',
    name: 'Classic Lieflat Waterline Contour',
    archetype: 'wave_ridge',
    category: 'Submersion Ridge',
    description: 'Multi-layer mountain ridge silhouette with dynamic waterline clipping and reflection.',
    dimensionality: '2D',
    tags: ['wave', 'waterline', 'contour'],
    recommendedFor: 'Visualizing cohort skill elevation above or below the danger waterline.',
    waterlineInteractive: true,
  },
  {
    id: 'wave-gaussian-density',
    name: 'Gaussian Joyplot Density Ridge',
    archetype: 'wave_ridge',
    category: 'Joyplot Density',
    description: 'Stacked kernel density estimates across longitudinal assessment milestones.',
    dimensionality: '2.5D',
    tags: ['wave', 'gaussian', 'joyplot'],
    recommendedFor: 'Tracking cohort grade distribution shifts from Week 1 to Week 16.',
    waterlineInteractive: true,
  },
  {
    id: 'wave-spectral-chromatic',
    name: 'Spectral Chromatic Wave',
    archetype: 'wave_ridge',
    category: 'Spectral Dispersion',
    description: 'Multi-frequency wave ribbon with optical color dispersion tied to velocity gradient.',
    dimensionality: '2D',
    tags: ['wave', 'spectral', 'chromatic'],
    recommendedFor: 'High-impact executive presentations and aesthetic data storytelling.',
    waterlineInteractive: false,
  },
  {
    id: 'wave-iso-depth-strata',
    name: 'Iso-Depth Bathymetric Strata',
    archetype: 'wave_ridge',
    category: 'Geological Strata',
    description: 'Segmented horizontal depth layers representing foundation, intermediate, and advanced mastery.',
    dimensionality: '2.5D',
    tags: ['wave', 'strata', 'bathymetric'],
    recommendedFor: 'Curriculum depth analysis and prerequisite mastery auditing.',
    waterlineInteractive: true,
  },
  {
    id: 'wave-wavelet-decimation',
    name: 'Wavelet Decimation Multiresolution Ridge',
    archetype: 'wave_ridge',
    category: 'Signal Processing',
    description: 'Haar wavelet decomposition separating high-frequency quiz noise from macro trends.',
    dimensionality: '2D',
    tags: ['wave', 'wavelet', 'decimation'],
    recommendedFor: 'Filtering noisy daily quiz scores to reveal true underlying student trajectory.',
    waterlineInteractive: true,
  },
  {
    id: 'wave-micro-turbulence',
    name: 'Micro-Turbulence Fluid Ripple',
    archetype: 'wave_ridge',
    category: 'Hydrodynamics',
    description: 'Perlin noise water turbulence reflecting active real-time student activity in chat.',
    dimensionality: '2.5D',
    tags: ['wave', 'turbulence', 'fluid'],
    recommendedFor: 'Live telemetry monitor during collaborative in-class exercises.',
    waterlineInteractive: false,
  },
  {
    id: 'wave-dual-cohort-divergence',
    name: 'Dual-Cohort Divergence Mirrored Ridge',
    archetype: 'wave_ridge',
    category: 'Comparative Ridge',
    description: 'Mirrored butterfly ridge comparing Fall 2025 vs Spring 2026 performance benchmarks.',
    dimensionality: '2D',
    tags: ['wave', 'divergence', 'cohort-comparison'],
    recommendedFor: 'Longitudinal curriculum reform evaluation and year-over-year pacing analysis.',
    waterlineInteractive: true,
  },
  {
    id: 'wave-velocity-acceleration-crest',
    name: 'Velocity Acceleration Crest',
    archetype: 'wave_ridge',
    category: 'Kinetic Wave',
    description: 'Wave crest steepness proportional to student acceleration (second derivative of score).',
    dimensionality: '2D',
    tags: ['wave', 'velocity', 'acceleration'],
    recommendedFor: 'Detecting students who are rapidly gaining momentum and ready for advanced topics.',
    waterlineInteractive: true,
  },
  {
    id: 'wave-translucent-hydroplane',
    name: 'Translucent Hydroplane Slicer',
    archetype: 'wave_ridge',
    category: 'Planar Slicing',
    description: 'Semi-transparent plane cutting through multi-subject ridges with cross-section readouts.',
    dimensionality: '2.5D',
    tags: ['wave', 'hydroplane', 'cross-section'],
    recommendedFor: 'Cross-disciplinary skill mapping across Math, Science, and English.',
    waterlineInteractive: true,
  },
  {
    id: 'wave-low-tide-horizon',
    name: 'Low-Tide Grounding Horizon',
    archetype: 'wave_ridge',
    category: 'Ground State',
    description: 'Receded waterline exposing underlying cognitive gaps normally masked by aggregate averages.',
    dimensionality: '2D',
    tags: ['wave', 'low-tide', 'gaps'],
    recommendedFor: 'Uncompromising pedagogical gap analysis prior to finals.',
    waterlineInteractive: true,
  },
  {
    id: 'wave-storm-surge-inundation',
    name: 'Storm-Surge Inundation Alert Ridge',
    archetype: 'wave_ridge',
    category: 'Crisis Detection',
    description: 'Dynamic red floodline rising when cohort-wide failure rates exceed safety tolerances.',
    dimensionality: '2D',
    tags: ['wave', 'storm-surge', 'alert'],
    recommendedFor: 'Institutional early warning escalation and Dean dashboard.',
    waterlineInteractive: true,
  },
  {
    id: 'wave-harmonic-resonance',
    name: 'Harmonic Resonance Standing Wave',
    archetype: 'wave_ridge',
    category: 'Physics Waves',
    description: 'Standing wave nodes marking stable concept mastery vs antinodes marking volatile topics.',
    dimensionality: '2.5D',
    tags: ['wave', 'resonance', 'standing-wave'],
    recommendedFor: 'Identifying curricular concepts that cause widespread instability.',
    waterlineInteractive: false,
  },

  // 4. LOLLIPOPS & STEM ALMANACS (12)
  {
    id: 'lollipop-baseline-grounded',
    name: 'Baseline Grounded Stem Almanac',
    archetype: 'lollipop_almanac',
    category: 'Stem Plot',
    description: 'Vertical stems anchored to zero baseline with circular bulbs colored by risk quartile.',
    dimensionality: '2D',
    tags: ['lollipop', 'stem', 'baseline'],
    recommendedFor: 'Clean, clutter-free ranking of student attendance and homework scores.',
    waterlineInteractive: true,
  },
  {
    id: 'lollipop-diverging-barbell',
    name: 'Diverging Zero-Mean Barbell',
    archetype: 'lollipop_almanac',
    category: 'Divergence',
    description: 'Horizontal stems extending left (below mean) or right (above mean) with dual status heads.',
    dimensionality: '2D',
    tags: ['lollipop', 'barbell', 'diverging'],
    recommendedFor: 'Highlighting relative positive/negative performance deviations from class average.',
    waterlineInteractive: true,
  },
  {
    id: 'lollipop-dual-head-threshold',
    name: 'Dual-Head Threshold Lollipop',
    archetype: 'lollipop_almanac',
    category: 'Threshold Pair',
    description: 'Single stem connecting pre-test bulb to post-test bulb, visualizing delta improvement.',
    dimensionality: '2D',
    tags: ['lollipop', 'pre-post', 'delta'],
    recommendedFor: 'Measuring instructional gain from diagnostic pre-test to midterm.',
    waterlineInteractive: true,
  },
  {
    id: 'lollipop-radial-polar-rose',
    name: 'Radial Polar Rose Lollipop',
    archetype: 'lollipop_almanac',
    category: 'Polar Plot',
    description: 'Circular compass radiating 360 degrees of student stems with waterline radius ring.',
    dimensionality: '2D',
    tags: ['lollipop', 'polar', 'rose', 'circular'],
    recommendedFor: 'Compact display of 100+ student profiles in an editorial circular format.',
    waterlineInteractive: true,
  },
  {
    id: 'lollipop-stepped-cadence',
    name: 'Stepped Attendance Cadence Stem',
    archetype: 'lollipop_almanac',
    category: 'Time Series',
    description: 'Lollipop stems arranged along chronological sprint intervals with step connector lines.',
    dimensionality: '2D',
    tags: ['lollipop', 'cadence', 'sprint'],
    recommendedFor: 'Weekly attendance audits during 4-week sprint retrospectives.',
    waterlineInteractive: true,
  },
  {
    id: 'lollipop-quartile-whiskered',
    name: 'Quartile Whiskered Stem',
    archetype: 'lollipop_almanac',
    category: 'Distribution',
    description: 'Lollipop bulb flanked by min-max error whiskers showing individual score variance.',
    dimensionality: '2D',
    tags: ['lollipop', 'whiskers', 'variance'],
    recommendedFor: 'Evaluating student consistency across multiple quiz attempts.',
    waterlineInteractive: false,
  },
  {
    id: 'lollipop-bioluminescent-bulb',
    name: 'Bioluminescent Glowing Bulb',
    archetype: 'lollipop_almanac',
    category: 'Aesthetic Light',
    description: 'Soft neon cyan and teal glowing bulbs that pulsate proportional to student velocity.',
    dimensionality: '2.5D',
    tags: ['lollipop', 'bioluminescent', 'glow'],
    recommendedFor: 'Ambient display installations on campus laboratory screens.',
    waterlineInteractive: true,
  },
  {
    id: 'lollipop-beaded-interval',
    name: 'Beaded Multi-Milestone Stem',
    archetype: 'lollipop_almanac',
    category: 'Multi-Valued',
    description: 'Vertical stem carrying multiple colored beads representing homework, midterm, and project.',
    dimensionality: '2D',
    tags: ['lollipop', 'beaded', 'multi-metric'],
    recommendedFor: 'Holistic tri-metric student evaluations on a single concise axis.',
    waterlineInteractive: true,
  },
  {
    id: 'lollipop-dynamic-risk-color',
    name: 'Continuous Dynamic Risk Spectrum Stem',
    archetype: 'lollipop_almanac',
    category: 'Heat Spectrum',
    description: 'Stem color smoothly interpolates from emerald (safe) to amber to crimson below waterline.',
    dimensionality: '2D',
    tags: ['lollipop', 'risk', 'color-spectrum'],
    recommendedFor: 'Instant pre-attentive detection of students in urgent need of academic support.',
    waterlineInteractive: true,
  },
  {
    id: 'lollipop-logarithmic-compression',
    name: 'Logarithmic Scaled Stem Almanac',
    archetype: 'lollipop_almanac',
    category: 'Scale Transform',
    description: 'Log-compressed stems accommodating heavy-tailed data such as API calls or study minutes.',
    dimensionality: '2D',
    tags: ['lollipop', 'logarithmic', 'heavy-tail'],
    recommendedFor: 'Analyzing student coding commit volume or LMS platform interaction clicks.',
    waterlineInteractive: false,
  },
  {
    id: 'lollipop-elastic-spring-tether',
    name: 'Elastic Spring Physics Tether',
    archetype: 'lollipop_almanac',
    category: 'Physics-Based',
    description: 'Stems rendered as spring coils with oscillatory physics upon mouse hover and drag.',
    dimensionality: '2.5D',
    tags: ['lollipop', 'spring', 'physics'],
    recommendedFor: 'Interactive exploratory dashboards that reward tactile user engagement.',
    waterlineInteractive: true,
  },
  {
    id: 'lollipop-clustered-cohort-dumbbell',
    name: 'Clustered Cohort Dumbbell Pair',
    archetype: 'lollipop_almanac',
    category: 'Cohort Pair',
    description: 'Paired bulbs on horizontal dumbbell comparing male vs female, or day vs night cohorts.',
    dimensionality: '2D',
    tags: ['lollipop', 'dumbbell', 'equity'],
    recommendedFor: 'Institutional equity and demographic parity auditing.',
    waterlineInteractive: true,
  },

  // 5. GLANCE & MICRO-SPRINT STRIPS (12)
  {
    id: 'glance-barcode-heatmap',
    name: 'High-Density Barcode Heatmap Strip',
    archetype: 'glance_sprint',
    category: 'Micro-Density',
    description: '1-pixel vertical bars per student packed horizontally into a compact 40px ribbon.',
    dimensionality: '2D',
    tags: ['glance', 'barcode', 'heatmap'],
    recommendedFor: 'Embedding complete 849-student cohorts in narrow table rows or header ribbons.',
    waterlineInteractive: true,
  },
  {
    id: 'glance-horizon-pulse-ribbon',
    name: 'Longitudinal Horizon Pulse Ribbon',
    archetype: 'glance_sprint',
    category: 'Horizon Graph',
    description: 'Mirrored positive/negative fold bands maximizing vertical resolution in micro spaces.',
    dimensionality: '2D',
    tags: ['glance', 'horizon', 'pulse'],
    recommendedFor: 'Tracking multi-week homework velocity curves without vertical screen clutter.',
    waterlineInteractive: true,
  },
  {
    id: 'glance-jitter-dot-matrix',
    name: 'Bounded Jitter Dot Strip',
    archetype: 'glance_sprint',
    category: 'Dot Plot',
    description: 'Beeswarm-style randomized micro-dots clustered around score median.',
    dimensionality: '2D',
    tags: ['glance', 'jitter', 'beeswarm'],
    recommendedFor: 'Revealing clusters, gaps, and outliers among individual student scores.',
    waterlineInteractive: true,
  },
  {
    id: 'glance-micro-sparkline-treadmill',
    name: 'Micro-Sparkline Treadmill Strip',
    archetype: 'glance_sprint',
    category: 'Sparkline',
    description: 'Miniature 8-point trend sparklines with color-coded final endpoints.',
    dimensionality: '2D',
    tags: ['glance', 'sparkline', 'trend'],
    recommendedFor: 'Quick-glance trajectory cards in teacher gradebook lists.',
    waterlineInteractive: false,
  },
  {
    id: 'glance-latency-interval-tic',
    name: 'Assignment Latency Interval Tic Tape',
    archetype: 'glance_sprint',
    category: 'Tick Plot',
    description: 'Tick tape strip recording submission times relative to midnight deadline.',
    dimensionality: '2D',
    tags: ['glance', 'ticks', 'deadline'],
    recommendedFor: 'Monitoring procrastination patterns and last-minute submission bottlenecks.',
    waterlineInteractive: false,
  },
  {
    id: 'glance-chrono-punch-tape',
    name: 'Ticker-Tape Chrono Punch Strip',
    archetype: 'glance_sprint',
    category: 'Ticker Tape',
    description: 'Continuous horizontal scrolling punch tape logging real-time student check-ins.',
    dimensionality: '2D',
    tags: ['glance', 'ticker', 'punch-tape'],
    recommendedFor: 'Live classroom kiosk display during morning entry.',
    waterlineInteractive: true,
  },
  {
    id: 'glance-quantum-state-bitmask',
    name: 'Quantum Risk State Bitmask',
    archetype: 'glance_sprint',
    category: 'Discrete States',
    description: 'Dense grid of discrete 4-bit status squares (0=Safe, 1=Watch, 2=Warn, 3=Critical).',
    dimensionality: '2D',
    tags: ['glance', 'bitmask', 'quantum-states'],
    recommendedFor: 'Automated administrative monitoring and compliance checklists.',
    waterlineInteractive: true,
  },
  {
    id: 'glance-waveform-attendance-ribbon',
    name: 'Waveform Audio-Style Attendance Ribbon',
    archetype: 'glance_sprint',
    category: 'Audio Analogy',
    description: 'Symmetric soundwave bars modulated by attendance percentage per student.',
    dimensionality: '2D',
    tags: ['glance', 'waveform', 'audio-analogy'],
    recommendedFor: 'Musical/rhythmic visual metaphor for classroom participation tempo.',
    waterlineInteractive: true,
  },
  {
    id: 'glance-rolling-mean-step-strip',
    name: 'Rolling Mean Stepwise Strip',
    archetype: 'glance_sprint',
    category: 'Moving Average',
    description: 'Stepped line strip showing 7-day moving averages with confidence corridors.',
    dimensionality: '2D',
    tags: ['glance', 'moving-average', 'steps'],
    recommendedFor: 'Smoothing daily attendance volatility to observe structural trends.',
    waterlineInteractive: false,
  },
  {
    id: 'glance-deficit-warning-beacon',
    name: 'Cognitive Deficit Warning Beacon Strip',
    archetype: 'glance_sprint',
    category: 'Warning Indicators',
    description: 'Pulsing beacon dots marking students whose mastery index dropped >15% this week.',
    dimensionality: '2D',
    tags: ['glance', 'beacon', 'warning'],
    recommendedFor: 'Priority triage list for academic counselors.',
    waterlineInteractive: true,
  },
  {
    id: 'glance-velocity-vector-chevron',
    name: 'Velocity Vector Chevron Chain',
    archetype: 'glance_sprint',
    category: 'Vector Glyphs',
    description: 'Directional arrow chevrons indicating acceleration direction and magnitude.',
    dimensionality: '2D',
    tags: ['glance', 'chevron', 'vectors'],
    recommendedFor: 'Intuitive glanceable progress indicators beside student names.',
    waterlineInteractive: true,
  },
  {
    id: 'glance-cohort-matrix-compact',
    name: 'Ultra-Compact Cohort 849 Cell Matrix',
    archetype: 'glance_sprint',
    category: 'Micro Matrix',
    description: 'Dense 28x30 square mosaic rendering all 849 students simultaneously.',
    dimensionality: '2D',
    tags: ['glance', 'mosaic', 'cohort-overview'],
    recommendedFor: 'Holistic single-screen institutional overview of the entire school population.',
    waterlineInteractive: true,
  },

  // 6. STREAMS & FUNNELS (10)
  {
    id: 'stream-giorgia-lupi-funnel',
    name: 'Giorgia Lupi Poured Funnel Stream',
    archetype: 'stream_funnel',
    category: 'Editorial Stream',
    description: 'Dual-cone organic hourglass funnel modeling semantic data compression to interventions.',
    dimensionality: '2.5D',
    tags: ['stream', 'funnel', 'hourglass', 'lupi'],
    recommendedFor: 'Editorial data art explaining agent reasoning and pedagogical pipeline stages.',
    waterlineInteractive: true,
  },
  {
    id: 'stream-symmetric-dual-cone',
    name: 'Symmetric Mathematical Dual-Cone',
    archetype: 'stream_funnel',
    category: 'Geometric Funnel',
    description: 'Exact hyperboloid of one sheet with neck radius r = 12px at central bottleneck.',
    mathFormula: '\\frac{x^2+y^2}{a^2} - \\frac{z^2}{c^2} = 1',
    dimensionality: '2.5D',
    tags: ['stream', 'dual-cone', 'hyperboloid'],
    recommendedFor: 'Scientific and engineering tracking of data ingestion throughput.',
    waterlineInteractive: true,
  },
  {
    id: 'stream-alluvial-transition-ribbon',
    name: 'Multi-Stage Alluvial Transition Ribbon',
    archetype: 'stream_funnel',
    category: 'Flow Alluvial',
    description: 'Flowing ribbon bands showing how students transition between grade tiers over time.',
    dimensionality: '2D',
    tags: ['stream', 'alluvial', 'sankey'],
    recommendedFor: 'Tracking cohort migration from midterm to final exam categories.',
    waterlineInteractive: true,
  },
  {
    id: 'stream-sankey-pedagogical',
    name: 'Sankey Pedagogical Conduit',
    archetype: 'stream_funnel',
    category: 'Resource Flow',
    description: 'Weighted branch flows from learning resources to skill assessments and mastery outcomes.',
    dimensionality: '2D',
    tags: ['stream', 'sankey', 'resources'],
    recommendedFor: 'Optimizing textbook and online curriculum resource allocation.',
    waterlineInteractive: false,
  },
  {
    id: 'stream-hydrodynamic-venturi',
    name: 'Hydrodynamic Venturi Tube',
    archetype: 'stream_funnel',
    category: 'Fluid Mechanics',
    description: 'Fluid constriction nozzle demonstrating velocity increase as data volume compresses.',
    dimensionality: '2.5D',
    tags: ['stream', 'venturi', 'fluid-flow'],
    recommendedFor: 'Explaining latency minimization in edge agent compute pipelines.',
    waterlineInteractive: true,
  },
  {
    id: 'stream-temporal-streamgraph',
    name: 'Continuous Baseline Streamgraph',
    archetype: 'stream_funnel',
    category: 'Streamgraph',
    description: 'Organic undulating stream with zero-sum baseline showing shifting subject mastery ratios.',
    dimensionality: '2D',
    tags: ['stream', 'streamgraph', 'curriculum'],
    recommendedFor: 'Visualizing relative growth across 5 academic disciplines simultaneously.',
    waterlineInteractive: true,
  },
  {
    id: 'stream-stepwise-funnel-attrition',
    name: 'Stepwise Funnel Attrition Cascade',
    archetype: 'stream_funnel',
    category: 'Conversion Funnel',
    description: 'Classic step funnel tracking drop-offs from enrolled -> active -> completed midterm.',
    dimensionality: '2D',
    tags: ['stream', 'funnel', 'attrition'],
    recommendedFor: 'Academic retention analysis and student onboarding diagnostics.',
    waterlineInteractive: false,
  },
  {
    id: 'stream-reverse-fountain-emergence',
    name: 'Reverse Fountain Emergence Stream',
    archetype: 'stream_funnel',
    category: 'Expansion Flow',
    description: 'Funnel inverting outwards from single teacher prompt into diverse student outputs.',
    dimensionality: '2.5D',
    tags: ['stream', 'fountain', 'divergence'],
    recommendedFor: 'Analyzing creative diversity in open-ended design and writing assignments.',
    waterlineInteractive: false,
  },
  {
    id: 'stream-inverted-dual-funnel',
    name: 'Inverted Dual-Funnel Counter-Flow',
    archetype: 'stream_funnel',
    category: 'Bidirectional Flow',
    description: 'Two opposing funnels representing teacher instructional input vs student feedback output.',
    dimensionality: '2.5D',
    tags: ['stream', 'dual-funnel', 'bidirectional'],
    recommendedFor: 'Evaluating reciprocal classroom feedback loops.',
    waterlineInteractive: true,
  },
  {
    id: 'stream-laminar-drift',
    name: 'Laminar Drift Layered Stream',
    archetype: 'stream_funnel',
    category: 'Laminar Fluid',
    description: 'Smooth, non-turbulent parallel fluid layers showing peaceful progression of mastery.',
    dimensionality: '2D',
    tags: ['stream', 'laminar', 'calm'],
    recommendedFor: 'Zen Focus mode and low-stress teacher review workflows.',
    waterlineInteractive: true,
  },

  // 7. FORCE-DIRECTED & NETWORKS (10)
  {
    id: 'force-student-skill-mesh',
    name: 'Bipartite Student-Skill Spring Mesh',
    archetype: 'force_network',
    category: 'Bipartite Graph',
    description: 'Simulated physical springs linking student nodes to curriculum skill concept nodes.',
    dimensionality: '2D',
    tags: ['force', 'network', 'bipartite', 'skills'],
    recommendedFor: 'Uncovering latent clustering between specific students and shared cognitive gaps.',
    waterlineInteractive: true,
  },
  {
    id: 'force-radial-constellation',
    name: 'Radial Skill Constellation Ring',
    archetype: 'force_network',
    category: 'Radial Network',
    description: 'Mastery skills arranged in circular halo with students pulled toward dominant skills.',
    dimensionality: '2.5D',
    tags: ['force', 'constellation', 'halo'],
    recommendedFor: 'Visualizing student specialization and elective track affinities.',
    waterlineInteractive: true,
  },
  {
    id: 'force-hierarchical-tree-branch',
    name: 'Prerequisite Curriculum Tree Network',
    archetype: 'force_network',
    category: 'Directed Acyclic Graph',
    description: 'Branching tree mapping prerequisite dependencies between foundational and advanced skills.',
    dimensionality: '2D',
    tags: ['force', 'dag', 'tree', 'prerequisites'],
    recommendedFor: 'Course syllabus design and verifying student readiness for next semester.',
    waterlineInteractive: false,
  },
  {
    id: 'force-louvain-cluster-rings',
    name: 'Louvain Modular Cluster Rings',
    archetype: 'force_network',
    category: 'Community Detection',
    description: 'Clusters students into autonomous study groups based on complementary skill deficits.',
    dimensionality: '2D',
    tags: ['force', 'louvain', 'clustering', 'study-groups'],
    recommendedFor: 'Automated peer tutoring matching and collaborative group formation.',
    waterlineInteractive: true,
  },
  {
    id: 'force-circular-chord-diagram',
    name: 'Circular Cross-Disciplinary Chord',
    archetype: 'force_network',
    category: 'Chord Diagram',
    description: 'Curved translucent ribbons connecting skills that frequently co-occur in failed exam items.',
    dimensionality: '2D',
    tags: ['force', 'chord', 'co-occurrence'],
    recommendedFor: 'Finding compound cognitive blockers that span across multiple questions.',
    waterlineInteractive: false,
  },
  {
    id: 'force-hyperbolic-poincare',
    name: 'Hyperbolic Poincare Disk Graph',
    archetype: 'force_network',
    category: 'Hyperbolic Space',
    description: 'Non-Euclidean projection allowing infinite hierarchy expansion within a bounded circle.',
    dimensionality: '2D',
    tags: ['force', 'poincare', 'hyperbolic'],
    recommendedFor: 'Exploring massive multi-tier curriculum taxonomies with 500+ standards.',
    waterlineInteractive: false,
  },
  {
    id: 'force-repulsion-island',
    name: 'Charge-Repulsion Island Archipelago',
    archetype: 'force_network',
    category: 'Island Clusters',
    description: 'Physics engine pushing distant cohorts into isolated topological islands on canvas.',
    dimensionality: '2.5D',
    tags: ['force', 'islands', 'repulsion'],
    recommendedFor: 'Detecting social learning silos and isolated student clusters.',
    waterlineInteractive: true,
  },
  {
    id: 'force-dynamic-flow-linkage',
    name: 'Dynamic Flow Linkage Graph',
    archetype: 'force_network',
    category: 'Link Trajectories',
    description: 'Animated particle pulses traveling along edges representing message exchanges.',
    dimensionality: '2D',
    tags: ['force', 'particles', 'flow-links'],
    recommendedFor: 'Monitoring peer interaction density in classroom discussion forums.',
    waterlineInteractive: true,
  },
  {
    id: 'force-centrality-hub-spoke',
    name: 'Eigenvector Centrality Hub & Spoke',
    archetype: 'force_network',
    category: 'Centrality',
    description: 'Identifies influential lead students whose attendance anchors peer cohort morale.',
    dimensionality: '2D',
    tags: ['force', 'centrality', 'influencers'],
    recommendedFor: 'Appointing student peer leaders and group project captains.',
    waterlineInteractive: true,
  },
  {
    id: 'force-submersion-pressure-lattice',
    name: 'Submersion Pressure Lattice Mesh',
    archetype: 'force_network',
    category: '3D Lattice',
    description: '3D elastic net sagging under gravitational weight of high-deficit student clusters.',
    dimensionality: '3D Submersion',
    tags: ['force', 'lattice', 'pressure', '3d'],
    recommendedFor: 'Spatial intuitive perception of curriculum points under highest student strain.',
    waterlineInteractive: true,
  },

  // 8. 3D SUBMERSION MANIFOLDS (10)
  {
    id: 'submersion-volumetric-elevation',
    name: 'Volumetric Mastery Elevation Terrain',
    archetype: 'submersion_3d',
    category: '3D Terrain',
    description: 'WebGL heightmap Z = f(Attendance, Homework, DINA) with dynamic waterline plane.',
    dimensionality: '3D Submersion',
    tags: ['submersion', '3d', 'terrain', 'heightmap'],
    recommendedFor: 'Primary interactive 3D exploration in the Petri Submersion Suite.',
    waterlineInteractive: true,
  },
  {
    id: 'submersion-waterline-breach-mesh',
    name: 'Dynamic Waterline Breach Surface',
    archetype: 'submersion_3d',
    category: 'Fluid Breach',
    description: 'Translucent blue-green water plane with caustic ripples and emergent student spheres.',
    dimensionality: '3D Submersion',
    tags: ['submersion', 'waterline', 'breach', 'caustics'],
    recommendedFor: 'Executive presentation of students breaching above danger line into mastery.',
    waterlineInteractive: true,
  },
  {
    id: 'submersion-particle-vortex-cyclone',
    name: 'Particle Vortex Cyclone Manifold',
    archetype: 'submersion_3d',
    category: 'Particle Physics',
    description: 'Swirling particle funnel accelerating toward bottom center as risk increases.',
    dimensionality: '3D Submersion',
    tags: ['submersion', 'particles', 'vortex'],
    recommendedFor: 'Visualizing rapid student disengagement spiral requiring immediate intervention.',
    waterlineInteractive: true,
  },
  {
    id: 'submersion-hyperplane-slicer',
    name: 'Quantum QSVC Hyperplane Slicer',
    archetype: 'submersion_3d',
    category: 'Machine Learning Plane',
    description: 'Tilted decision hyperplane separating passing from failing students based on QSVC model.',
    dimensionality: '3D Submersion',
    tags: ['submersion', 'qsvc', 'hyperplane', 'svm'],
    recommendedFor: 'Proving quantum-assisted support vector machine classification boundary.',
    waterlineInteractive: true,
  },
  {
    id: 'submersion-topographic-wireframe',
    name: 'Topographic Contour Wireframe',
    archetype: 'submersion_3d',
    category: 'Wireframe Contour',
    description: 'Clean monochrome cyan wireframe mesh with isoline elevation rings.',
    dimensionality: '3D Submersion',
    tags: ['submersion', 'wireframe', 'topographic'],
    recommendedFor: 'High-performance rendering on low-power mobile devices and tablets.',
    waterlineInteractive: true,
  },
  {
    id: 'submersion-voxel-density-lattice',
    name: 'Voxel Grid Density Lattice',
    archetype: 'submersion_3d',
    category: 'Voxel Volume',
    description: '3D volumetric cubes with alpha transparency proportional to student density.',
    dimensionality: '3D Submersion',
    tags: ['submersion', 'voxel', '3d-density'],
    recommendedFor: 'Volumetric clustering of 1,000+ multidimensional student vectors.',
    waterlineInteractive: true,
  },
  {
    id: 'submersion-archimedean-dive',
    name: 'Archimedean Spiral Camera Dive',
    archetype: 'submersion_3d',
    category: 'Kinetic Camera',
    description: 'Camera flight trajectory descending into deep sub-waterline strata.',
    dimensionality: '3D Submersion',
    tags: ['submersion', 'camera-flight', 'dive'],
    recommendedFor: 'Hyperframe video studio camera trajectory integration.',
    waterlineInteractive: true,
  },
  {
    id: 'submersion-multilayer-strata-core',
    name: 'Multi-Layer Strata Geological Core',
    archetype: 'submersion_3d',
    category: 'Geological Core',
    description: 'Cylindrical borehole core sample cutting through 4 curricular strata layers.',
    dimensionality: '3D Submersion',
    tags: ['submersion', 'borehole', 'core-sample'],
    recommendedFor: 'Deep diagnostic audit of individual student longitudinal history.',
    waterlineInteractive: true,
  },
  {
    id: 'submersion-bathymetric-trench',
    name: 'Bathymetric Deep Oceanic Trench',
    archetype: 'submersion_3d',
    category: 'Deep Trench',
    description: 'Deep abyss terrain mapping severe multi-semester dropouts requiring crisis counseling.',
    dimensionality: '3D Submersion',
    tags: ['submersion', 'trench', 'abyss'],
    recommendedFor: 'High-severity intervention tracking across multi-year cohorts.',
    waterlineInteractive: true,
  },
  {
    id: 'submersion-dual-cone-hourglass-3d',
    name: '3D Dual-Cone Hourglass Core',
    archetype: 'submersion_3d',
    category: 'Volumetric Hourglass',
    description: 'Fully rotatable 3D wireframe hourglass with falling golden sand particle stream.',
    dimensionality: '3D Submersion',
    tags: ['submersion', 'hourglass', 'sand-particles', '3d'],
    recommendedFor: 'Signature Petri visual symbol bridging chat telemetry with git delivery.',
    waterlineInteractive: true,
  },

  // 9. HIERARCHICAL & COMPOSITIONAL PARTITIONS (10)
  {
    id: 'hier-submersion-treemap',
    name: 'Submersion Sliced Treemap',
    archetype: 'hierarchical_partition',
    category: 'Treemap',
    description: 'Proportional tiles sizing course modules by enrollment, submerged under danger waterline.',
    dimensionality: '2D',
    tags: ['treemap', 'hierarchical', 'modules'],
    recommendedFor: 'Departmental budget and instructional resource capacity allocation.',
    waterlineInteractive: true,
  },
  {
    id: 'hier-nested-sunburst',
    name: 'Multi-Level Nested Sunburst',
    archetype: 'hierarchical_partition',
    category: 'Sunburst',
    description: 'Concentric hierarchy rings: School -> Department -> Course -> Skill.',
    dimensionality: '2D',
    tags: ['sunburst', 'nested', 'radial'],
    recommendedFor: 'Navigating large academic program structures with drill-down clicks.',
    waterlineInteractive: false,
  },
  {
    id: 'hier-voronoi-tessellation',
    name: 'Voronoi Cellular Tessellation',
    archetype: 'hierarchical_partition',
    category: 'Voronoi',
    description: 'Organic polygon cells generated by student skill centroid proximity.',
    dimensionality: '2D',
    tags: ['voronoi', 'tessellation', 'polygons'],
    recommendedFor: 'Visually striking territorial maps of student mastery zones.',
    waterlineInteractive: true,
  },
  {
    id: 'hier-mosaic-proportion',
    name: 'Two-Way Mosaic Marimekko Plot',
    archetype: 'hierarchical_partition',
    category: 'Marimekko',
    description: 'Variable width and height tiles showing demographic breakdown across score quartiles.',
    dimensionality: '2D',
    tags: ['mosaic', 'marimekko', 'contingency'],
    recommendedFor: 'Cross-tabulation demographic parity analysis.',
    waterlineInteractive: false,
  },
  {
    id: 'hier-bubble-pack-cluster',
    name: 'Circle Packing Cohort Cluster',
    archetype: 'hierarchical_partition',
    category: 'Circle Packing',
    description: 'Enclosing circles nesting student bubbles inside homeroom sections.',
    dimensionality: '2D',
    tags: ['bubble-pack', 'nesting', 'circles'],
    recommendedFor: 'Playful and intuitive classroom roster visualization.',
    waterlineInteractive: true,
  },
  {
    id: 'hier-circular-dendrogram',
    name: 'Circular Cladogram Dendrogram',
    archetype: 'hierarchical_partition',
    category: 'Dendrogram',
    description: 'Phylogenetic-style radial tree showing hierarchical clustering of learner archetypes.',
    dimensionality: '2D',
    tags: ['dendrogram', 'cladogram', 'clustering'],
    recommendedFor: 'Unsupervised machine learning cluster hierarchy exploration.',
    waterlineInteractive: false,
  },
  {
    id: 'hier-icicle-waterfall',
    name: 'Icicle Hierarchy Waterfall',
    archetype: 'hierarchical_partition',
    category: 'Icicle Plot',
    description: 'Top-down cascading rectangles representing curriculum taxonomy breakdown.',
    dimensionality: '2D',
    tags: ['icicle', 'waterfall', 'breakdown'],
    recommendedFor: 'Clean horizontal hierarchy reading without circular distortion.',
    waterlineInteractive: true,
  },
  {
    id: 'hier-radial-partition-arc',
    name: 'Radial Partition Arc Dial',
    archetype: 'hierarchical_partition',
    category: 'Arc Partition',
    description: 'Gauged angular arcs measuring completion status per course competency.',
    dimensionality: '2D',
    tags: ['radial-partition', 'arc', 'progress'],
    recommendedFor: 'High-level degree audit dashboards.',
    waterlineInteractive: false,
  },
  {
    id: 'hier-layered-density-pyramid',
    name: 'Bloom Taxonomy Mastery Pyramid',
    archetype: 'hierarchical_partition',
    category: 'Pyramid',
    description: 'Stepped pyramid tracking student ascension from Knowledge -> Application -> Synthesis.',
    dimensionality: '2.5D',
    tags: ['pyramid', 'bloom-taxonomy', 'levels'],
    recommendedFor: 'Assessing higher-order cognitive mastery vs rote recall.',
    waterlineInteractive: true,
  },
  {
    id: 'hier-flame-graph-stack',
    name: 'Cognitive Execution Flame Graph',
    archetype: 'hierarchical_partition',
    category: 'Flame Graph',
    description: 'Software-style flame graph displaying time spent per student on each assessment phase.',
    dimensionality: '2D',
    tags: ['flame-graph', 'latency', 'profiling'],
    recommendedFor: 'Pinpointing exact bottlenecks where students stalled during exams.',
    waterlineInteractive: false,
  },

  // 10. TACTICAL MATRICES & MULTIAXIAL VIEWS (10)
  {
    id: 'matrix-correlation-heatmap',
    name: 'Curricular Skill Correlation Matrix',
    archetype: 'tactical_matrix',
    category: 'Correlation',
    description: 'Symmetric Pearson r matrix heatmap between attendance, homework, and test scores.',
    dimensionality: '2D',
    tags: ['matrix', 'correlation', 'pearson'],
    recommendedFor: 'Identifying which early homework assignments best predict midterm outcomes.',
    waterlineInteractive: false,
  },
  {
    id: 'matrix-confusion-precision',
    name: 'QSVC Classifier Confusion Matrix',
    archetype: 'tactical_matrix',
    category: 'Classification Metrics',
    description: 'True Positives, False Positives, and ROC AUC metrics for early warning predictions.',
    dimensionality: '2D',
    tags: ['matrix', 'confusion-matrix', 'roc-auc'],
    recommendedFor: 'Proving accuracy and minimizing false alarms in early intervention systems.',
    waterlineInteractive: false,
  },
  {
    id: 'matrix-parallel-coordinates',
    name: 'Multi-Dimensional Parallel Coordinates',
    archetype: 'tactical_matrix',
    category: 'Parallel Coordinates',
    description: 'Polyline per student crossing 6 parallel vertical axes with interactive brush filtering.',
    dimensionality: '2D',
    tags: ['matrix', 'parallel-coordinates', 'brushing'],
    recommendedFor: 'Deep multidimensional querying and finding rare student edge-case combinations.',
    waterlineInteractive: true,
  },
  {
    id: 'matrix-radar-multiaxial',
    name: 'Holistic Student Competency Radar',
    archetype: 'tactical_matrix',
    category: 'Radar / Spider',
    description: 'Equilateral pentagon plotting Attendance, Homework, Midterm, DINA, and Velocity.',
    dimensionality: '2D',
    tags: ['matrix', 'radar', 'spider', 'pentagon'],
    recommendedFor: 'Individual student parent-teacher conference summary report cards.',
    waterlineInteractive: true,
  },
  {
    id: 'matrix-splom-scatter-pairs',
    name: 'Pairwise Scatterplot Matrix (SPLOM)',
    archetype: 'tactical_matrix',
    category: 'SPLOM',
    description: 'NxN grid of all pairwise 2D scatter plots with diagonal density histograms.',
    dimensionality: '2D',
    tags: ['matrix', 'splom', 'pairwise-scatter'],
    recommendedFor: 'Data scientist deep exploration of full institutional datasets.',
    waterlineInteractive: false,
  },
  {
    id: 'matrix-andrews-curve-projection',
    name: 'Fourier Andrews Curve Projection',
    archetype: 'tactical_matrix',
    category: 'Andrews Curves',
    description: 'Transforms multidimensional student vectors into smooth periodic Fourier waves.',
    mathFormula: 'f_i(t) = \\frac{x_1}{\\sqrt{2}} + x_2\\sin(t) + x_3\\cos(t) + x_4\\sin(2t) + \\dots',
    dimensionality: '2D',
    tags: ['matrix', 'andrews', 'fourier', 'high-dimensional'],
    recommendedFor: 'Detecting subtle multivariate clusters without losing information to PCA projection.',
    waterlineInteractive: true,
  },
  {
    id: 'matrix-chernoff-cognitive-faces',
    name: 'Chernoff Cognitive Glyphs',
    archetype: 'tactical_matrix',
    category: 'Chernoff Glyphs',
    description: 'Facial feature geometry (smile curvature, eye height) mapped to attendance and scores.',
    dimensionality: '2D',
    tags: ['matrix', 'chernoff', 'glyphs'],
    recommendedFor: 'Pre-attentive empathy-driven student wellbeing checkins.',
    waterlineInteractive: false,
  },
  {
    id: 'matrix-ternary-triangle',
    name: 'Ternary Tri-Metric Triangle Plot',
    archetype: 'tactical_matrix',
    category: 'Ternary Plot',
    description: 'Equilateral barycentric triangle plotting ratios of Theory, Lab Practice, and Attendance.',
    dimensionality: '2D',
    tags: ['matrix', 'ternary', 'barycentric', 'triangle'],
    recommendedFor: 'Balancing vocational vs theoretical student learning styles.',
    waterlineInteractive: true,
  },
  {
    id: 'matrix-biplot-pca',
    name: 'Principal Components Biplot (PCA)',
    archetype: 'tactical_matrix',
    category: 'PCA Biplot',
    description: 'Projects 849 students onto PC1 vs PC2 axes with vector arrows for curriculum variables.',
    dimensionality: '2D',
    tags: ['matrix', 'pca', 'biplot', 'dimension-reduction'],
    recommendedFor: 'Determining the 2 primary mathematical axes driving student variation.',
    waterlineInteractive: true,
  },
  {
    id: 'matrix-umap-embedding',
    name: 'Nonlinear UMAP Embedding Scatter',
    archetype: 'tactical_matrix',
    category: 'UMAP Manifold',
    description: 'Nonlinear topological dimensionality reduction preserving local and global community clusters.',
    dimensionality: '2.5D',
    tags: ['matrix', 'umap', 'manifold', 'clustering'],
    recommendedFor: 'Frontier AI semantic clustering of multi-modal student learning histories.',
    waterlineInteractive: true,
  },
];

class LieflatCatalogService {
  private catalog: ChartOptionDefinition[] = [...LIEFLAT_100_CHART_CATALOG];

  getAllCharts(): ChartOptionDefinition[] {
    return [...this.catalog];
  }

  getChartsByArchetype(archetype: LieflatArchetype): ChartOptionDefinition[] {
    return this.catalog.filter((c) => c.archetype === archetype);
  }

  getChartById(id: string): ChartOptionDefinition | undefined {
    return this.catalog.find((c) => c.id === id);
  }

  searchCharts(query: string, archetype?: LieflatArchetype): ChartOptionDefinition[] {
    const q = query.trim().toLowerCase();
    return this.catalog.filter((c) => {
      const matchesArchetype = !archetype || c.archetype === archetype;
      if (!matchesArchetype) return false;
      if (!q) return true;
      return (
        c.name.toLowerCase().includes(q) ||
        c.description.toLowerCase().includes(q) ||
        c.category.toLowerCase().includes(q) ||
        c.tags.some((t) => t.toLowerCase().includes(q))
      );
    });
  }

  getArchetypes() {
    return LIEFLAT_ARCHETYPES_METADATA;
  }
}

export const lieflatCatalogService = new LieflatCatalogService();
